---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-metrics-reader
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-metrics-reader
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-metrics-reader-binding
subjects:
- kind: ServiceAccount
  name: pod-metrics-reader
  namespace: default
roleRef:
  kind: Role
  name: pod-metrics-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cost-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-cost-manager
  template:
    metadata:
      labels:
        app: pod-cost-manager
    spec:
      serviceAccountName: pod-metrics-reader
      containers:
        - name: golang-app
          image: pod-cost-manager:0.1.0
          env:
            - name: APPLICATIONS
              value: "app1,app2"
          ports:
            - containerPort: 8080
